version: '3.1'

services:

  db:
    image: postgres
    container_name: postgres_database
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example

  db_webinterface:
    image: fenglc/pgadmin4
    container_name: postgres_webinterface
    restart: always
    links: 
      - db:postgres
    ports:
      - 5050:5050
    environment:
      DEFAULT_USER: example
      DEFAULT_PASSWORD: example

  python:
    container_name: python_context
    build:
      context: .
      dockerfile: python.dockerfile
    environment:
      DATABASE_SERVER: db
      DATABASE_SERVER_PORT: 5432
      ENTRYPOINT_DATABASE_NAME: postgres
      DATABASE_USER: example
      DATABASE_USER_PASSWORD: example
      TARGET_DATABASE_NAME: chicago_taxi
      RAW_DATATABLE_NAME: raw_data
      COMPANYNAME_TABLE_NAME: company_name
      PICKUP_LATITUDE_TABLE_NAME: pickup_latitude
      PICKUP_LONGITUDE_TABLE_NAME: pickup_longitude
      DROPOFF_LATITUDE_TABLE_NAME: dropoff_latitude
      DROPOFF_LONGITUDE_TABLE_NAME: dropoff_longitude
  dss:
    image: dataiku/dss
    container_name: dss
    ports:
      - 10000:10000